repo: "button-styles"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 3
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - "a.btn"
    search:
      - "Primary button"
      - "Subtle button"
      - "Ghost button"
      - "Warning button"
      - "button small"
      - "button big"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['.btn', 'display', 'inline-block']
      - ['.btn:hover']
      - ['.btn-small', 'font-size']
      - ['.btn-big', 'font-size']
      - ['.btn-subtle']
      - ['.btn-subtle:hover']
      - ['.btn-ghost']
      - ['.btn-ghost:hover']
      - ['.btn-warning']
      - ['.btn-warning:hover']
    has_not:
      - ['.btn-small', ['padding', 'display', 'background-color', 'border-radius', 'border', 'color', 'text-decoration']]
      - ['.btn-big', ['padding', 'display', 'background-color', 'border-radius', 'border', 'color', 'text-decoration']]
      - ['.btn-subtle', ['padding', 'display', 'border-radius', 'border', 'text-decoration']]
      - ['.btn-ghost', ['padding', 'display', 'border-radius', 'border', 'text-decoration']]
      - ['.btn-warning', ['padding', 'display', 'border-radius', 'border', 'text-decoration']]

screenshots:
  - path: "index.html"
    sizes: [400]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('div:first-child a');
        let oldBg = css(link).backgroundColor;

        hover('div:first-child a', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the first button doesn’t change when hovered')
          pass();
        });

      - |
        let link = $('div:nth-child(2) a');
        let oldBg = css(link).backgroundColor;

        hover('div:nth-child(2) a', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the second button doesn’t change when hovered')
          pass();
        });

      - |
        let link = $('div:nth-child(3) a');
        let oldBg = css(link).backgroundColor;

        hover('div:nth-child(3) a', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the third button doesn’t change when hovered')
          pass();
        });
