repo: "button-styles"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - box-sizing

html:
  - path: "index.html"
    outline: false
    has:
      - "a.btn"
    search:
      - "Primary button"
      - "Subtle button"
      - "Ghost button"
      - "Warning button"
      - "button small"
      - "button big"

css:
  - path: "css/main.css"
    has:
      - ['.btn', 'display', 'inline-block']
      - ['.btn:hover']
      - ['.btn-small', 'font-size']
      - ['.btn-big', 'font-size']
      - ['.btn-subtle']
      - ['.btn-subtle:hover']
      - ['.btn-ghost']
      - ['.btn-ghost:hover']
      - ['.btn-warning']
      - ['.btn-warning:hover']
    has_not:
      - ['.btn-small', ['padding', 'display', 'background-color', 'border-radius', 'border', 'color', 'text-decoration']]
      - ['.btn-big', ['padding', 'display', 'background-color', 'border-radius', 'border', 'color', 'text-decoration']]
      - ['.btn-subtle', ['padding', 'display', 'border-radius', 'border', 'text-decoration', 'font-size']]
      - ['.btn-ghost', ['padding', 'display', 'border-radius', 'border', 'text-decoration', 'font-size']]
      - ['.btn-warning', ['padding', 'display', 'border-radius', 'border', 'text-decoration', 'font-size']]
    search_not:
      - '\.btn-subtle-small'
      - '\.btn-small-subtle'
      - '\.btn-big-subtle'
      - '\.btn-subtle-big'
      - '\.btn-ghost-small'
      - '\.btn-small-ghost'
      - '\.btn-big-ghost'
      - '\.btn-ghost-big'
      - '\.btn-warning-small'
      - '\.btn-small-warning'
      - '\.btn-big-warning'
      - '\.btn-warning-big'

screenshots:
  - path: "index.html"
    sizes: [400]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('div:first-child a');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the first button doesn’t change when hovered')
          pass();
        });

      - |
        let link = $('div:nth-child(2) a');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the second button doesn’t change when hovered')
          pass();
        });

      - |
        let link = $('div:nth-child(3) a');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the third button doesn’t change when hovered')
          pass();
        });
